#include "globals/mcl_const.hpp"

// MCL constants
 int NUM_PARTICLES = 500;

 float DISTANCE_RIGHT_CONSTANT = 1.0f;
 float DISTANCE_LEFT_CONSTANT = 1.0f;
 float DISTANCE_FRONT_CONSTANT = 1.0f;
 float DISTANCE_BACK_CONSTANT = 1.0f;

 float DISTANCE_RIGHT_OFFSET_X = 5.25f;
 float DISTANCE_RIGHT_OFFSET_Y = -3.0f;
 float DISTANCE_RIGHT_OFFSET_T = 90.0f;

 float DISTANCE_LEFT_OFFSET_X = -5.25f;
 float DISTANCE_LEFT_OFFSET_Y = -3.0f;
 float DISTANCE_LEFT_OFFSET_T = -90.0f;

 float DISTANCE_FRONT_OFFSET_X = 4.25f;
 float DISTANCE_FRONT_OFFSET_Y = 5.0f;
 float DISTANCE_FRONT_OFFSET_T = 0.0f;

 float DISTANCE_BACK_OFFSET_X = -3.25f;
 float DISTANCE_BACK_OFFSET_Y = -4.0f;
 float DISTANCE_BACK_OFFSET_T = 180.0f;  