#include "globals/mcl_const.hpp"

// MCL constants
 int NUM_PARTICLES = 500;

 float DISTANCE_RIGHT_CONSTANT = 1.0f;
 float DISTANCE_LEFT_CONSTANT = 1.0f;
 float DISTANCE_FRONT_CONSTANT = 1.0f;
 float DISTANCE_BACK_CONSTANT = 1.0f;

 float DISTANCE_RIGHT_OFFSET_X = 6.5f;
 float DISTANCE_RIGHT_OFFSET_Y = 2.15f;
 float DISTANCE_RIGHT_OFFSET_T = 90.0f;

 float DISTANCE_LEFT_OFFSET_X = -6.0f;
 float DISTANCE_LEFT_OFFSET_Y = 0.6f;
 float DISTANCE_LEFT_OFFSET_T = -90.0f;

 float DISTANCE_FRONT_OFFSET_X = -3.0f;
 float DISTANCE_FRONT_OFFSET_Y = 10.0f;
 float DISTANCE_FRONT_OFFSET_T = 0.0f;

 float DISTANCE_BACK_OFFSET_X = -4.4f;
 float DISTANCE_BACK_OFFSET_Y = -1.7f;
 float DISTANCE_BACK_OFFSET_T = 180.0f;  